#!/bin/bash

shopt -s nocasematch

query="{query}"
[ $query = "{query}" ] && query="$@"

xml="$(system_profiler SPBluetoothDataType -xml | plutil -extract '0._items.0.device_title' xml1 -o - -)"
count=$(xmllint --xpath  "count(/plist/array/dict)" <(echo $xml))

echo '<?xml version="1.0"?>'
echo '<items>'
for i in $(seq $count); do
  device=$(xmllint --xpath "/plist/array/dict[$i]/key/text()" <(echo $xml))
  if [[ -n $query && ! $device =~ $query ]]; then
    continue
  fi
  connected=$(xmllint --xpath "/plist/array/dict[$i]/dict/key[.=\"device_isconnected\"]/following-sibling::*[1]/text()" <(echo $xml))
  if [ "$connected" == "attrib_Yes" ]; then
    action="Disconnect"
  else
    action="Connect"
  fi
  cat <<_END_OF_ITEM_
  <item uid="$device" arg="$device">
    <title>$device</title>
    <subtitle>$action $device</subtitle>
  </item>
_END_OF_ITEM_
done
echo '</items>'
